### ISSUE TITLE
Empty users in channel query

### ISSUE THREAD

**Issue by lineldcosta** [tabvn/nodejs-reactjs-chatapp#2]
Hey i am very very big follower(Medium) of your YouTube series. Thanks for the great videos.

I got an issue for the same git code.
```

db.getCollection('channels').aggregate({
                        $lookup: {
                            from: 'users',
                            localField: 'members',
                            foreignField: '_id',
                            as: 'users',
                        }
                    },
                    {
                        $match: {
                            members: {$all: [ObjectId("5a54de8d70c542516cb95209")]}
                        }
                    },
                    {
                        $project: {
                            _id: true,
                            title: true,
                            lastMessage: true,
                            created: true,
                            updated: true,
                            userId: true,
                            users: {
                                _id: true,
                                name: true,
                                created: true,
                                online: true
                            },
                            members: true,
                        }
                    },
                    {
                        $sort: {updated: -1, created: -1}
                    },
                    {
                        $limit: 50,
                    })
```

Result
```
{
    "_id" : ObjectId("5a550a641071c900003c4521"),
    "title" : "",
    "lastMessage" : "ss\n",
    "created" : ISODate("2018-01-09T18:31:30.241Z"),
    "userId" : ObjectId("5a54ff26babde666e1aedaac"),
    "members" : [ 
        ObjectId("5a54ff26babde666e1aedaac"), 
        ObjectId("5a550183e1444e6f68c43c0c")
    ],
    "updated" : ISODate("2018-01-09T18:31:49.752Z"),
    "users" : []
}

```

Any idea how to solve this.

(But i saw u were able to get the records for **users** [i am using mongodb 3.2 version] Any clue how to resolve this since i have never used mongodb before)

**Comment by lineldcosta** [comment]
After upgrading to 3.4 version it works cool now,,,

**Comment by suribabubetabulls** [comment]
Hi 
Thanks for the nice app. I run separately it's working fine but i integrated server side code to my app node server getting issue.
Actually i m using ECMA 5 , i 'm getting error import is unexpected . 
I installed all modules as per package.json but not resolve . I installed and setup ECMA 6 but getting same error.
please help me how to solve the issue.

Thanks
Suribabu

**Comment by lineldcosta** [comment]
which version of nodejs you are using?

**Comment by tabvn** [comment]
suribabubetabulls , lineldcosta in my video i did use node 8.x however i guess 9.x work fine no problem. However there is issue is mongodb in package must use 2.x if u are using 3.x it should be same , but must diffrent when we make connect to db , see the docs: http://mongodb.github.io/node-mongodb-native/3.0/quick-start/quick-start/

**Comment by suribabubetabulls** [comment]
Hi

Thanks for the reply, My node version is 6.10.0. It is existing application
i need to add chat app. if I change node version previous functionality is
working fine right? Because of i'm using ECMA 5 .


Thanks

**Comment by suribabubetabulls** [comment]
Hi
Thanks for the reply, My node version is 6.10.0. It is existing application
i need to add chat app. if I change node version previous functionality is
working fine right? Because of i'm using ECMA 5 .

**Comment by lineldcosta** [comment]
Try, It will work.. if not we will fix
